version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile

    volumes:
      - .:/nexaworldweb
    restart: always
    ports:
      - 3000:3000
    command: npm run dev
